# Análisis Exploratorio de Datos - Campañas de Marketing Bancario

El objetivo de este proyecto es limpiar y analizar los datos de campañas de marketing de una entidad bancaria para identificar patrones y factores que influyen en la contratación de productos.

1. IMPORTACIÓN DE LIBRERÍAS

Primero, instalar pandas (y openpyxl), matplotlib y seaborn en la terminal con pip install, luego importar las librerías necesarias:

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

2. CARGA DE DATOS

In [2]:
df = pd.read_csv("../data/RAW/bank-additional.csv")
excel = pd.ExcelFile("../data/RAW/customer-details.xlsx")

df1 = pd.read_excel(excel, sheet_name=0)
df2 = pd.read_excel(excel, sheet_name=1)
df3 = pd.read_excel(excel, sheet_name=2)

df_clientes = pd.concat([df1, df2, df3])

3. EXPLORACIÓN INICIAL

En este apartado, el objetivo es tener una imágen clara sobre las BBDD, sus columnas, valores y formatos, para poder realizar la limpieza correspondiente. Para ello, usamos funcionemos como head, info, describe. En este punto, también podemos detectar la cantidad de nulos por columna con los que vamos a trabajar, y así determinar el tratamiento que se le dará a cada uno.

In [3]:
df.head()

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,...,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,...,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,...,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,...,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,...,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [4]:
df_clientes.head()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43000 non-null  int64
 1   age             37880 non-null  float64
 2   job             42655 non-null  object
 3   marital         42915 non-null  object
 4   education       41193 non-null  object
 5   default         34019 non-null  float64
 6   housing         41974 non-null  float64
 7   loan            41974 non-null  float64
 8   contact         43000 non-null  object
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  object
 14  emp.var.rate    43000 non-null  float64
 15  cons.price.idx  42529 non-null  object
 16  cons.conf.idx   43000 non-null  object
 17  euribor3m       33744 non-null  object
 18  nr.employed     43000 non-null  object
 19  y               43000 non-null  object
 20  date            42752 non-null  object
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id_             43000 non-null  object
dtypes: float64(7), int64(5), object(12)
memory usage: 7.9+ MB

In [6]:
df_clientes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43170 entries, 0 to 14089
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         43170 non-null  int64
 1   Income             43170 non-null  int64
 2   Kidhome            43170 non-null  int64
 3   Teenhome           43170 non-null  int64
 4   Dt_Customer        43170 non-null  datetime64[ns]
 5   NumWebVisitsMonth  43170 non-null  int64
 6   ID                 43170 non-null  object
dtypes: datetime64[ns](1), int64(5), object(1)
memory usage: 2.6+ MB

In [7]:
df.describe()

,Unnamed: 0,age,default,housing,loan,duration,campaign,pdays,previous,emp.var.rate,latitude,longitude
count,43000.000000,37880.000000,34019.000000,41974.000000,41974.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000
mean,20651.099047,39.977112,0.000088,0.535998,0.155620,257.739279,2.567233,962.330953,0.174023,0.077128,36.856697,-95.939067
std,11868.770913,10.437957,0.009390,0.498708,0.362499,258.666033,2.772294,187.260394,0.497366,1.573898,7.225948,16.752282
min,0.000000,17.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,-3.400000,24.396000,-124.997000
25%,10381.750000,32.000000,0.000000,0.000000,0.000000,102.000000,1.000000,999.000000,0.000000,-1.800000,30.614750,-110.494250
50%,20642.500000,38.000000,0.000000,1.000000,0.000000,179.000000,2.000000,999.000000,0.000000,1.100000,36.761000,-95.899500
75%,30930.250000,47.000000,0.000000,1.000000,0.000000,319.000000,3.000000,999.000000,0.000000,1.400000,43.113250,-81.427750
max,41187.000000,98.000000,1.000000,1.000000,1.000000,4918.000000,56.000000,999.000000,7.000000,1.400000,49.384000,-66.937000

In [8]:
df_clientes.describe()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
count,43170.000000,43170.000000,43170.000000,43170.000000,43170,43170.000000
mean,7916.022469,93227.389622,1.004749,0.998633,2013-05-11 22:09:47.407922176,16.591290
min,0.000000,5841.000000,0.000000,0.000000,2012-01-01 00:00:00,1.000000
25%,3597.000000,49608.000000,0.000000,0.000000,2012-07-16 00:00:00,9.000000
50%,7194.500000,93009.500000,1.000000,1.000000,2013-03-01 00:00:00,17.000000
75%,11705.750000,136740.500000,2.000000,2.000000,2014-03-28 00:00:00,25.000000
max,20114.000000,180802.000000,2.000000,2.000000,2014-12-31 00:00:00,32.000000
std,5228.248885,50498.181989,0.815996,0.816008,NaN,9.241769

In [9]:
df.isnull().sum()

Unnamed: 0           0
age               5120
job                345
marital             85
education         1807
default           8981
housing           1026
loan              1026
contact              0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx     471
cons.conf.idx        0
euribor3m         9256
nr.employed          0
y                    0
date               248
latitude             0
longitude            0
id_                  0
dtype: int64

In [10]:
df_clientes.isnull().sum()

Unnamed: 0           0
Income               0
Kidhome              0
Teenhome             0
Dt_Customer          0
NumWebVisitsMonth    0
ID                   0
dtype: int64

4. LIMPIEZA INICIAL

Cuando ya tenemos claro los valores con los que trabajamos, nos centramos en que cada uno tenga el formato correspondiente y eliminamos las columnas que no aporten al análisis.

In [11]:
# Eliminar la columna "Unnamed: 0", índice innecesario
df = df.drop(columns=["Unnamed: 0"])
df_clientes = df_clientes.drop(columns=["Unnamed: 0"])

In [12]:
# Convertir la variable objetivo "y" a numérica, donde "yes" se convierte en 1 y "no" en 0 para facilitar el análisis.
df["y"] = df["y"].map({"yes": 1, "no": 0})

In [13]:
# Convertir los valores de las columnas numéricas a tipo numérico, ya que al leer el CSV se interpretaron como objetos (strings), en el excel los formatos están correctos.
cols = ["cons.price.idx", "cons.conf.idx", "euribor3m"]

for col in cols:
    df[col] = df[col].str.replace(",", ".").astype(float)

# Tuve que reemplazar las comas por puntos para convertir los valores a tipo numérico, ya que en el CSV los números decimales estaban representados con comas, por lo que me daba error al intentar convertirlos directamente a float.

In [14]:
# Convertir la columna "date" a formato datetime, primero traduciendo los meses del español al inglés para que pandas pueda interpretarlos correctamente.
meses = {
    'enero': 'Jan', 'febrero': 'Feb', 'marzo': 'Mar', 'abril': 'Apr',
    'mayo': 'May', 'junio': 'Jun', 'julio': 'Jul', 'agosto': 'Aug',
    'septiembre': 'Sep', 'octubre': 'Oct', 'noviembre': 'Nov', 'diciembre': 'Dec'
}

df['date_en'] = df['date']
for es, en in meses.items():
    df['date_en'] = df['date_en'].str.replace(es, en, regex=True)

df['date'] = pd.to_datetime(df['date_en'], dayfirst=True)

df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['weekday'] = df['date'].dt.day_name()

df.drop(columns=['date_en'], inplace=True)

# En este punto me dio error al intentar convertir la columna "date" a formato datetime, ya que los meses estaban en español y pandas no los reconocía. Por eso tuve que crear una nueva columna "date_en" donde reemplacé los nombres de los meses en español por sus equivalentes en inglés, para luego poder convertir esa columna a datetime sin problemas. Después extraje el año, mes, día y día de la semana en nuevas columnas para facilitar el análisis temporal. Finalmente eliminé la columna "date_en" ya que solo era un paso intermedio para la conversión.

In [15]:
# En la tabla de df_clientes, la columna "Dt_Customer" ya está en formato datetime, así que solo necesito extraer el día, mes y año en nuevas columnas para facilitar el análisis temporal.

df_clientes["day"] = df_clientes["Dt_Customer"].dt.day
df_clientes["month"] = df_clientes["Dt_Customer"].dt.month
df_clientes["year"] = df_clientes["Dt_Customer"].dt.year

In [16]:
# Verificamos los cambios realizados
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             37880 non-null  float64
 1   job             42655 non-null  object
 2   marital         42915 non-null  object
 3   education       41193 non-null  object
 4   default         34019 non-null  float64
 5   housing         41974 non-null  float64
 6   loan            41974 non-null  float64
 7   contact         43000 non-null  object
 8   duration        43000 non-null  int64
 9   campaign        43000 non-null  int64
 10  pdays           43000 non-null  int64
 11  previous        43000 non-null  int64
 12  poutcome        43000 non-null  object
 13  emp.var.rate    43000 non-null  float64
 14  cons.price.idx  42529 non-null  float64
 15  cons.conf.idx   43000 non-null  float64
 16  euribor3m       33744 non-null  float64
 17  nr.employed     43000 non-null  object
 18  y               43000 non-null  int64
 19  date            42752 non-null  datetime64[ns]
 20  latitude        43000 non-null  float64
 21  longitude       43000 non-null  float64
 22  id_             43000 non-null  object
 23  year            42752 non-null  float64
 24  month           42752 non-null  float64
 25  day             42752 non-null  float64
 26  weekday         42752 non-null  object
dtypes: datetime64[ns](1), float64(13), int64(5), object(8)
memory usage: 8.9+ MB

In [17]:
df.head(2)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,nr.employed,y,date,latitude,longitude,id_,year,month,day,weekday
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,...,5191,0,2019-08-02,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079,2019.0,8.0,2.0,Friday
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,...,5191,0,2016-09-14,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097,2016.0,9.0,14.0,Wednesday

In [18]:
df_clientes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43170 entries, 0 to 14089
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Income             43170 non-null  int64
 1   Kidhome            43170 non-null  int64
 2   Teenhome           43170 non-null  int64
 3   Dt_Customer        43170 non-null  datetime64[ns]
 4   NumWebVisitsMonth  43170 non-null  int64
 5   ID                 43170 non-null  object
 6   day                43170 non-null  int32
 7   month              43170 non-null  int32
 8   year               43170 non-null  int32
dtypes: datetime64[ns](1), int32(3), int64(4), object(1)
memory usage: 2.8+ MB

In [19]:
df_clientes.head(2)

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID,day,month,year
0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079,4,4,2012
1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097,30,12,2012

5. MANEJO DE VALORES NULOS Y OUTLIERS

Para terminar con la limpieza de las tablas, es necesario tomar decisiones sobre el manejo de los valores nulos y outliers, ya que el correcto manejo de estos es escenial para el posterior análisis de los mismos.

In [20]:
# Para menajar los nulos en "age", decidí relacionarlo directamente con "marital", para ello, primero rellené los valores faltantes de "marital" con la moda.

df['marital'].fillna(df['marital'].mode()[0], inplace=True)

C:\Users\rscon\AppData\Local\Temp\ipykernel_26856\970925120.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['marital'].fillna(df['marital'].mode()[0], inplace=True)

In [22]:
# Para rellenar los valores nulos de "age", utilicé la función transform de pandas para aplicar una función lambda que rellena los valores faltantes con la mediana de "age" dentro de cada grupo de "marital". De esta manera, los valores nulos en "age" se rellenan de manera más precisa, teniendo en cuenta la relación entre el estado civil y la edad.
df['age'] = df.groupby('marital')['age'].transform(lambda x: x.fillna(x.median()))

In [23]:
# Para menajar los nulos de "job" y "education" decidí reemplazarlos por la palabra "unknown".

df['job'].fillna('unknown', inplace=True)
df['education'].fillna('unknown', inplace=True)

C:\Users\rscon\AppData\Local\Temp\ipykernel_26856\3587243606.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['job'].fillna('unknown', inplace=True)
C:\Users\rscon\AppData\Local\Temp\ipykernel_26856\3587243606.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['education'].fillna('unknown', inplace=True)

In [24]:
# Para los nulos de "default", "housing" y "loan", decidí rellenarlos con -1, ya que son variables binarias y no quiero introducir una categoría adicional como "unknown", además de que -1 me permitirá identificarlos fácilmente en el análisis posterior.

df['default'].fillna(-1, inplace=True)
df['housing'].fillna(-1, inplace=True)
df['loan'].fillna(-1, inplace=True)

C:\Users\rscon\AppData\Local\Temp\ipykernel_26856\1145854314.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['default'].fillna(-1, inplace=True)
C:\Users\rscon\AppData\Local\Temp\ipykernel_26856\1145854314.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['housing'].fillna(-1, inplace=True)
C:\Users\rscon\AppData\Local\Temp\ipykernel_26856\1145854314.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['loan'].fillna(-1, inplace=True)

In [25]:
# Para manejar los nulos de "cons.price.idx", decidí rellenarlos con la media de la columna, ya que no son muchos nulos y la media es una buena opción para este tipo de variable numérica continua.

df['cons.price.idx'].fillna(df['cons.price.idx'].mean(), inplace=True)

C:\Users\rscon\AppData\Local\Temp\ipykernel_26856\3306233650.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['cons.price.idx'].fillna(df['cons.price.idx'].mean(), inplace=True)

In [27]:
# Para manejar los nulos de la columna "date", al ser un dato importante para el análisis temporal, y al ser tan poco nulos (248 nulos, el 0.5% del total de filas), decidí eliminar las filas que contienen nulos en esta columna, ya que no afectará significativamente el análisis y me permitirá trabajar con datos completos en las fechas.

df = df.dropna(subset=['date'])

In [ ]:
# Para manejar los nulos en la columna "euribor3m", decidí rellenarlos con el último valor conocido, ordenando primero de forma descendente la columna "cons.price.idx".

df = df.sort_values('cons.price.idx', ascending=False)
df['euribor3m'] = df['euribor3m'].fillna(method='ffill')

C:\Users\rscon\AppData\Local\Temp\ipykernel_26856\720462147.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['euribor3m'] = df['euribor3m'].fillna(method='ffill')

In [29]:
#Comprobamos los nulos después de la limpieza
df.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
date              0
latitude          0
longitude         0
id_               0
year              0
month             0
day               0
weekday           0
dtype: int64